### ISSUE TITLE
Error in gpt-4

### ISSUE THREAD

**Issue by puritynetwork** [danny-avila/chatgpt-clone#101]
I tried changing model to gpt-4 but it gives me this error:

L'errore è questo:

Error message: Failed to send message. HTTP 404 - {
  "error": {
    "message": "This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?",
    "type": "invalid_request_error",
    "param": "model",
    "code": null
  }
}

**Comment by danny-avila** [comment]
Sadly this project is not using the latest package for node-chatgpt-api as there are some breaking changes for us. I would like to try each updated version and see which exactly allows gpt-4 but I don't have a gpt-4 key to test.

https://github.com/waylaidwanderer/node-chatgpt-api/issues/208

**Comment by puritynetwork** [comment]
> Sadly this project is not using the latest package for node-chatgpt-api as there are some breaking changes for us. I would like to try each updated version and see which exactly allows gpt-4 but I don't have a gpt-4 key to test.
> 
> [waylaidwanderer/node-chatgpt-api#208](https://github.com/waylaidwanderer/node-chatgpt-api/issues/208)

I have it

**Comment by danny-avila** [comment]
> I have it

you can try upgrade the npm package @waylaidwanderer/node-chatgpt-api incrementally. i know the latest update will break functionality though

**Comment by danny-avila** [comment]
@puritynetwork good news, you should be able to set it after my update today

**Comment by puritynetwork** [comment]
> 



> @puritynetwork good news, you should be able to set it after my update today

Ok, i try

**Comment by danny-avila** [comment]
I'm closing for now, since your specific issue should be solved, but i will make gpt-4 an option in the model menu soon
