### ISSUE TITLE
404 Not Found nginx/1.22.1

### ISSUE THREAD

**Issue by Omar07Ibarhim** [danny-avila/chatgpt-clone#116]
I get error 404 Not Found nginx/1.22.1 in http://localhost:3080/auth/login
Help me please

**Comment by danny-avila** [comment]
Are you running with docker or local? Latest release on main branch? You can make sure to set the user system variable explicitly false too

**Comment by Omar07Ibarhim** [comment]
ENABLE_USER_SYSTEM= false right ? 
And can you share your telegram ?

**Comment by danny-avila** [comment]
Yes but make sure there’s no space between = and false so “=false”

I don’t have telegram but you can join the discord server https://discord.gg/vQVuPwt2nc

**Comment by danny-avila** [comment]
Also clear your site data and cookies I found that helps

**Comment by danny-avila** [comment]
Please let me know if this remains an issue as it should be completely taken care of as of #118

**Comment by danny-avila** [comment]
haven't heard back and I managed to reproduce the error and fix it. Closing.
