### ISSUE TITLE
Continuous dialogue increase switch

### ISSUE THREAD

**Issue by voctot** [danny-avila/chatgpt-clone#129]
Can you make a switch for continuous dialogue, because the continuous dialogue is too wasteful token.

**Comment by danny-avila** [comment]
I’m not sure what you mean

**Comment by voctot** [comment]
> I’m not sure what you mean, do you mean max token limit?

The API request will carry the previous record every time. I want to have a switch to control it. Do not carry records when request. This is conducive to saving costs

**Comment by danny-avila** [comment]
Unfortunately that is not possible with the response streaming. You can only limit tokens with max tokens setting and provided stop sequences. I’m working on customization parameters for both those features

https://help.openai.com/en/articles/5072263-how-do-i-use-stop-sequences

https://help.openai.com/en/articles/5072263-how-do-i-use-stop-sequences

**Comment by voctot** [comment]
> 不幸的是，这对于响应流是不可能的。您只能使用最大令牌设置和提供的停止序列来限制令牌。我正在研究这两个功能的自定义参数
> 
> https://help.openai.com/en/articles/5072263-how-do-i-use-stop-sequences
> 
> https://platform.openai.com/docs/guides/chat

well
