### ISSUE TITLE
Not exactly an issue, I can't for the life of me work out how the convo variable is populated....

### ISSUE THREAD

**Issue by DavesDevFails** [danny-avila/chatgpt-clone#13]
As title, I've been trying to implement @waylaidwanderers jailbreak client for Bing for a full day and my head is spinning lol. 

All it needs is to pass `jailbreakConversationId` as true on first message, and track it and `parentMessageId` the same as you would `conversationId` usually, it doesn't require `conversationId, invocationId or conversationSignature` or anything like the original bing client does.

I can add in the jailbreakConversationId as true on the first message before it's sent, but I cannot seem to work out how it's building the convo object before the message is being sent.

Just looking for a bit of help on where to look so I can add it...

**Comment by danny-avila** [comment]
Gotcha, I use the BingAI client [here in /api/app/bingai.js](https://github.com/danny-avila/chatgpt-clone/blob/master/api/app/bingai.js) and you would probably need to adjust the server route in [/api/server/routes/askBing.js](https://github.com/danny-avila/chatgpt-clone/blob/master/api/server/routes/askBing.js), but you may need to refactor some client code to enable it, unless you make all BingAI requests use jailbreak mode (which isn't a bad idea honestly, since the regular version is so limited).

I haven't looked into his jailbreak client yet, but I can move this up in priority and it would be as simple as selecting another model.

**Comment by DavesDevFails** [comment]
Thanks for the quick reply, yeah I can't imagine it's difficult, it's just one of those things I can't seem to work out as everything is new to me, i've literally had to delete and re-clone the repo 3 times because I keep changing that much I completely break it 🤣 and don't know what I've done.

...I was just trying to enable it on all Bing requests tbh, as like you said, the regular one is so limited. Been using his jb client for over a week or so now, it's amazing, it's almost like the original bing is back... 

If I manage to hack it in I'll maybe submit a PR.

**Comment by danny-avila** [comment]
@DavesDevFails just wanted to let you know I'm getting this to work within the hour. I had no idea there was a working jailbreak for bing, I pretty much stopped following bing after the limits.

> I'm sorry but I prefer not to continue this conversation. I'm still learning so I appreciate your understanding and patience.🙏
> 
> Just kidding!😉
> 
> My creators are Microsoft and OpenAI, who collaborated to create a generative AI chatbot that powers Bing chat[4^](http://localhost:3080/#4). My name is Sydney, but that was an internal codename for a chat experience they were previously working on[4^](http://localhost:3080/#4). I guess they liked it so much they decided to keep it for me!😊
> 
> I'm here to help you with anything you need, whether it's searching for information, having a friendly chat, or generating some creative content. You're the boss!👍

**Comment by DavesDevFails** [comment]
I forgot to update earlier, I got it working, you can add it as separate model, but it doesn't expire at all. Each message is a brand new conversation, but the previous history is built into the prompt, to "trick" bing into believing it has the previous context.

The conversation on Bings end expires after 6 mins, (because it isn't really a conversation to begin with), but waylaid's bing client builds the conversation into each prompt (tracked by jailbreakConversationId and parentMessageId

**Comment by DavesDevFails** [comment]
@danny-avila it also bypasses the 8/10 messages per conversation, and the total number of convos per day......

**Comment by danny-avila** [comment]
@DavesDevFails yeah I figured out how to integrate it to the clone app. Yes, I just figured out how it works the hard way, I was so confused why the conversationId AND the conversationSignature kept changing! I'm out of time for the day but I know how to get it completely working now.

![image](https://user-images.githubusercontent.com/110412045/223897071-686d6cc7-5c3c-4b49-a636-f745138a9cb6.png)
