### ISSUE TITLE
the dialog box for customGPT exceeds the page range

### ISSUE THREAD

**Issue by wind2sing** [danny-avila/chatgpt-clone#130]
If the prompt prefix for the customGPT is very long, the dialog box will exceed the page range. In this case, we won't be able to see the buttons and we can't scroll up or down the page.

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/66316949/227781715-170adfa9-8168-4028-9912-75c9f3f2c107.png">

**Comment by danny-avila** [comment]
Gotcha this should be an easy fix with max width thanks for reporting this
