### ISSUE TITLE
view or modify prompts for existing CustomGPT

### ISSUE THREAD

**Issue by wind2sing** [danny-avila/chatgpt-clone#131]
After we finish setting up multiple customGPTs, how can we view or modify the prompt prefix for one of them? It seems that currently we can only modify its name.

**Comment by danny-avila** [comment]
I believe You can modify the prompt as long as you match the label. But I will make this more apparent in a coming update

**Comment by wind2sing** [comment]
Thank you danny. I know that if I fill in a CustomGPT label, I can override and modify it.
But there is a situation where after setting up a new CustomGPT for some time, I forgot what its instructions were. Is there a way to simply find out what its instructions are or make minor modifications?

**Comment by danny-avila** [comment]
We've made significant progress on this, still in development 
![image](https://user-images.githubusercontent.com/110412045/229319971-1cff4538-26dd-48d0-a9fa-27a79dcc8520.png)

**Comment by danny-avila** [comment]
Finished in #142
