### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by Kryvexa** [danny-avila/chatgpt-clone#144]
Add a database ("mysql" I'm better with cpanel) I would like you to create a synchronization system with google login or create a dedicated login and registration page with captcha .. Let me know if I would like to add this system 

(then add the SQL database configuration in the .env file and the key for google access
each chat ID links to the account ID in SQL Database
)

------

Add the same GPT 3.5 and GPT-4 editing template as on ChatGPT (for gpt4 in the .env file change the gpt-4 model as the user wants (8K or 32K token)

------

add a "FALSE" or "TRUE" on file .env to make sure that I can decide whether to display the box to select GPT-4

------
make sure to install everything in the root directory without going through folders one by one

example:

C:\Users\\%username%\Desktop\chatgpt-clone>npm install
and
C:\Users\\%username%\Desktop\chatgpt-clone>npm start

------

I like this project
 
Thanks.
Chris.

**Comment by wtlyu** [comment]
![image-2](https://user-images.githubusercontent.com/8267138/229333401-f8ce8ecd-fc4e-4014-b388-8069534dac29.png)

working in progress. will coming soon.


as for req 4, maybe it's not available. since server and client is definitely different and separate project.

**Comment by wtlyu** [comment]
we have no time to support more database. because it require to change the database engine and huge refactoring, with little benefit. user don't need to touch anything of db, how it's important to you？

**Comment by wtlyu** [comment]
btw. personally I prefer mysql than mongodb

**Comment by Kryvexa** [comment]
thanks for the replies.. i have little experience with mongo

so can you add the sync system with mongo?

so I don't lose anything if I change my device

**Comment by danny-avila** [comment]
> thanks for the replies.. i have little experience with mongo
> 
> from requests I had made with mysql can you do it with mongo?
> 
> so I don't lose anything if I change my device

Yes, you can achieve similar functionality with MongoDB that you can with MySQL. MongoDB is a NoSQL, document-oriented database, and synchronization across schema is possible. You can theoretically host the MongoDB service anywhere the project can query, and there is a remote service called mongo atlas that services this.

I don't plan to make an advanced Access control list or admin panel so I can't guarantee it will be exactly what you're requesting. There are people making their own user systems like that with the current project code, so you are at liberty to make it yourself.

What I do plan is a simple multi-user system that will allow registration/logging in/auth through google, microsoft, potentially discord too. It will most likely be a separate branch from main but will strongly adhere to the main branch by staying up to date with it
