### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '/client/dist/index.html'

### ISSUE THREAD

**Issue by bing2008** [danny-avila/chatgpt-clone#146]
Hello sir,

When i pull new version and run with docker cmd "docker-compose up", and browse the url,
it says "Not Found" in the page, and the console shows:
`"chatgpt-clone-api-1          | Error: ENOENT: no such file or directory, stat '/client/dist/index.html'"`

Any advice about it?

**Comment by danny-avila** [comment]
> Hello sir,
> 
> When i pull new version and run with docker cmd "docker-compose up", and browse the url, it says "Not Found" in the page, and the console shows: `"chatgpt-clone-api-1 | Error: ENOENT: no such file or directory, stat '/client/dist/index.html'"`
> 
> Any advice about it?

did you pull the latest update to main? This was an issue and it was fixed.

**Comment by danny-avila** [comment]
Just ran `docker-compose up` with latest update to main and no issue

**Comment by bing2008** [comment]
FROM node:19-alpine AS react-client
WORKDIR /client
# copy package.json into the container at /client
COPY /client/package*.json /client/
# install dependencies
RUN npm ci
# Copy the current directory contents into the container at /client
COPY /client/ /client/
# Build webpack artifacts
RUN npm run build

FROM node:19-alpine AS node-api
WORKDIR /api
# copy package.json into the container at /api
COPY /api/package*.json /api/
# install dependencies
RUN npm ci
# Copy the current directory contents into the container at /api
COPY /api/ /api/
# Copy the client side code
COPY --from=react-client /client/dist /client/dist
# Make port 3080 available to the world outside this container
EXPOSE 3080
# Expose the server to 0.0.0.0
ENV HOST=0.0.0.0
# Run the app when the container launches
CMD ["npm", "start"]

# Optional: for client with nginx routing
FROM nginx:stable-alpine AS nginx-client
WORKDIR /usr/share/nginx/html
COPY --from=react-client /client/public /usr/share/nginx/html
# Add your nginx.conf
COPY /client/nginx.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT ["nginx", "-g", "daemon off;"]

**Comment by danny-avila** [comment]
I think I may know the issue before trying a fix.

**Comment by danny-avila** [comment]
can you make sure to delete the docker container you already had, and then delete the node-api image? Not sure if you are using docker desktop, but using that GUI will make it easier. 

After doing that, goto the docker container and inspect the api-1 files. let me know what is in the client folder

![image](https://user-images.githubusercontent.com/110412045/229551700-f8761619-e62a-4400-8b4e-d024f9c41f36.png)


![image](https://user-images.githubusercontent.com/110412045/229551653-d2fdc17a-b434-4081-b6b7-274b4f0d83d7.png)

**Comment by bing2008** [comment]
I am using a debain operating system, and i had try to use "docker-compose down" and "docker-compose rm" command delete the container, before using "docker-compose up" comand to create and start the container.

**Comment by danny-avila** [comment]
maybe it has the images cached because the only thing that makes sense to me is to delete the image as well before doing compose up after an update to the project

**Comment by bing2008** [comment]
Here is the folder of clients:
```
/api # ls app/clients
bingai.js           chatgpt-browser.js  chatgpt-client.js   chatgpt-custom.js   sydney.js
```

But i think i found the reason of this issue: Nodejs build failure in my system.
When i use "docker-compose up --build" to force build the code, it say FATAL ERROR.

```
#0 34.85 <--- JS stacktrace --->
#0 34.85
#0 34.86 FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
#0 36.24 npm ERR! path /client
#0 36.24 npm ERR! command failed
#0 36.24 npm ERR! signal SIGABRT
#0 36.24 npm ERR! command sh -c vite build
#0 36.25
#0 36.25 npm ERR! A complete log of this run can be found in:
#0 36.25 npm ERR!     /root/.npm/_logs/2023-04-03T16_01_06_729Z-debug-0.log
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
```

So maybe my server's memory is too low, it's only has 1G memory.
I will try enlarge the memory and try again.

**Comment by danny-avila** [comment]
Oh I meant  .client/ not .api/clients but yes looks like it definitely is the build error

**Comment by bing2008** [comment]
Oh, the .client/ folder like this, has no dist folder in it. so same conclusion~
```
/ # ls client
node_modules  public
```

**Comment by danny-avila** [comment]
Let me know if you got this working with more memory
