### ISSUE TITLE
Unable to edit or send new messages when there is an error

### ISSUE THREAD

**Issue by adamrb** [danny-avila/chatgpt-clone#152]
When the API returns an error, I'm unable to edit my message or type a new message.

Steps to reproduce:
1. Ask ChatGPT to summarize a large quantity of text (eg: a YouTube transcript)
2. Get this error

```
An error occurred. Please try again in a few moments.

Error message: Failed to send message. HTTP 413 - {"detail":{"message":"The message you submitted was too long, please reload the conversation and submit something shorter.","code":"message_length_exceeds_limit"}}
```

4. Get stuck and have to start a new thread

**Comment by danny-avila** [comment]
so every time you try to edit your message, you get this same error?

**Comment by adamrb** [comment]
I missed the edit button (since the text was so long), sorry about that!
