### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '/client/dist/index.html'

### ISSUE THREAD

**Issue by hbsgithub** [danny-avila/chatgpt-clone#159]
I pull the lastest version, but when I excute docker-compose up, and open the web, it logs as follow:
api_1          | Error: ENOENT: no such file or directory, stat '/client/dist/index.html'

**Comment by hbsgithub** [comment]
I solve the problem by excuting the following command:
`docker-compose up --build`

**Comment by danny-avila** [comment]
> I solve the problem by excuting the following command:
> `docker-compose up --build`

Thanks! I will change the instructions based on this since we are actively updating this
