### ISSUE TITLE
Markdown firmatting errors

### ISSUE THREAD

**Issue by antonme** [danny-avila/chatgpt-clone#162]
It seems that there are some errors with Markdown formatting:
Table | List
:-------------------------:|:-------------------------:
<img width="612" alt="Screenshot 2023-04-06 at 18 10 34" src="https://user-images.githubusercontent.com/1531009/230422371-2c170877-fea1-4954-819c-2860b3128ede.png"> | <img width="612" alt="Screenshot 2023-04-06 at 18 11 09" src="https://user-images.githubusercontent.com/1531009/230422389-e4a7a57f-0287-477c-a129-bb2660bd556f.png">

The longer the table is, the larger the space appears before it. 
100% reproducible for me in Chrome, Safari, and Firefox.

**Comment by danny-avila** [comment]
This has been a known issue for a while and it finally dawned on me why it was happening. The table issue was key. Thanks lmk it should be gone
