### ISSUE TITLE
How to set the access password?

### ISSUE THREAD

**Issue by fjliss** [danny-avila/chatgpt-clone#169]
How to set the access password in the access page? Otherwise, it's easy for search engines like google to sniff out.

**Comment by danny-avila** [comment]
Not sure what you mean by being sniffed out? You need to build your own user system at this point before we build authentication out of the box

**Comment by danny-avila** [comment]
Closing as this is not an issue about the current state of the repo. We will build a user system soon enough, though

**Comment by fjliss** [comment]
think you very much

**Comment by fjliss** [comment]
thank you very much
