### ISSUE TITLE
new chat - first message, ai responds, seemingly completes and receive status 429 (seems like issue with saving as conversation)

### ISSUE THREAD

**Issue by ptrang** [danny-avila/chatgpt-clone#17]
ran docker instructions w/ updated tokens
set up a free instance of mongodb atlas e.g. connection string: mongodb+srv://user:pass@db.letnum#s.mongodb.net/?retryWrites=true
upon finishing the first message in convo

happens for both bing and chatgpt models, exact same error message
"An error occurred. Please try again in a few moments.

Error message: Request failed with status code 429"
removed keys from [chatgpt-clone-issue-1.txt](https://github.com/danny-avila/chatgpt-clone/files/10939777/chatgpt-clone-issue-1.txt)

IMO, it's trying to save the response as a conversation but runs 429 "too many requests" while doing so

**Comment by ptrang** [comment]
adding bing model error logs - [bing-error-429.txt](https://github.com/danny-avila/chatgpt-clone/files/10939998/bing-error-429.txt)

why do the urls keep saying openai when i'm supposed to be hitting bing api?

**Comment by danny-avila** [comment]
Thanks for reporting this with this level of detail. I may have overlooked handling the conversation titling (which is why there’s an open ai request). I was already planning to give a setting to disable it since it uses tokens to do so.

I will try to recreate it with your instructions, since I also haven’t tried atlas with docker

**Comment by danny-avila** [comment]
@ptrang Atlas works fine with docker. Error 429 is a rate limiting error from openAI, have you tried a different key? Either way, the default behavior will be to title with 'New Chat' if there is an error when titling the conversation, so you shouldn't even need a key anymore and instead use the free models.

**Comment by ptrang** [comment]
@danny-avila pulled latest commit, updated the settings in yml file, downloaded chrome fresh.  this is what i get:
An error occurred. Please try again in a few moments.

Error message: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.22.1</center>
</body>
</html>

**Comment by ptrang** [comment]
i assume it is related to docker.  if I try locally, i do not get 502 bad gateway
