### ISSUE TITLE
Posting before the bot finishes writing

### ISSUE THREAD

**Issue by antonme** [danny-avila/chatgpt-clone#175]
If you post a message while the model is still writing, it just disappears with no way to get it back. It seems that it should not be possible to post while ChatGPT is still writing its answer.

**Comment by danny-avila** [comment]
You're right, this was the original functionality but something stopped it between development. Working on this issue and the other issue you mentioned on discord

**Comment by wtlyu** [comment]
What.. how to post while a model is writing?

**Comment by antonme** [comment]
> What.. how to post while a model is writing?

Enter the message, press return

**Comment by danny-avila** [comment]
> > What.. how to post while a model is writing?
> 
> Enter the message, press return

Do you mean the message you type disappears when you press enter while the response is generating? I fixed this in #177 (not yet live), but wanted to confirm again that this is the issue

**Comment by antonme** [comment]
> Do you mean the message you type disappears when you press enter while the response is generating? I fixed this in #177 (not yet live), but wanted to confirm again that this is the issue

Yeah, that's right (and reproduceable)

**Comment by danny-avila** [comment]
addressed in #177
