### ISSUE TITLE
The query line loses focus during a conversation in BingAI

### ISSUE THREAD

**Issue by antonme** [danny-avila/chatgpt-clone#180]
When the response changes from streaming to a downloaded version with sources, the focus shifts from the query line to the chat list. As a result, to continue the conversation, you must click on the query line again. This must be done each time, making it impossible to have a keyboard-only conversation

**Comment by danny-avila** [comment]
So this issue has been bugging me for ages. I finally have a solution but it requires a PR to node-chatgpt-api
