### ISSUE TITLE
Has this project been published on Docker Hub?

### ISSUE THREAD

**Issue by Passerby1011** [danny-avila/chatgpt-clone#182]
Has this project been published on Docker Hub?I want to deploy it on my NAS, and it would be much easier if it has been published on Docker Hub.

**Comment by danny-avila** [comment]
No it hasn’t but I can get around to it soon. Will report back here when it is

**Comment by danny-avila** [comment]
Done here, now live and the default for docker-compose: https://github.com/danny-avila/chatgpt-clone/commit/f5ff91cfbd3e679151d6693f158e1c503dad0f90
