### ISSUE TITLE
Is there some place in this project that is leaking memory

### ISSUE THREAD

**Issue by kuangxiaoye** [danny-avila/chatgpt-clone#184]
If there are too many users, they will die.

About ten people use it at the same time

**Comment by danny-avila** [comment]
Possibly the search feature, it’s really not optimized for multi-user support. Do you have it enabled? Do you know if it dies as soon as 10 people use it or after specific use?

There could be other areas since this hasn’t been developed yet. We are working on adding a prebuilt user system and then I’ll be debugging and running tests to address issues like this.

since you have a user system in place, if you find anything, PRs are welcome. I know of at least one other fork with multi-user support and they have no issues as far as I know with search disabled, and I have ideas on how to address this since it was made with one user in mind.

**Comment by kuangxiaoye** [comment]
> Possibly the search feature, it’s really not optimized for multi-user support. Do you have it enabled? Do you know if it dies as soon as 10 people use it or after specific use?
> 
> There could be other areas since this hasn’t been developed yet. We are working on adding a prebuilt user system and then I’ll be debugging and running tests to address issues like this.
> 
> since you have a user system in place, if you find anything, PRs are welcome. I know of at least one other fork with multi-user support and they have no issues as far as I know with search disabled, and I have ideas on how to address this since it was made with one user in mind.

Thank you very much for your reply, I underestimated the resource usage of this code....

In order to save resources, I changed the file cache to redis,But frequent io operations make the small machine completely uncontrollable····

I'm trying to localize the conversation store in browser

The server configuration is as follows:

1H1.5G50G

**Comment by danny-avila** [comment]
Thanks for your work on this, too. 

> In order to save resources, I changed the file cache to redis,But frequent io operations make the small machine completely uncontrollable····
> 
> I'm trying to localize the conversation store in browser
> 

On this point, if the store cache is the issue, could this help with client side caching? (Keyv)

https://kikobeats.com/client-side-caching/

> The server configuration is as follows:
> 
> 1H1.5G50G

I'm not sure what this means


I'm new to scaling systems, so for me, I will cross that bridge soon as there is work by another contributor adding multi-user to the repo

**Comment by danny-avila** [comment]
Also if the store is causing memory issues at scale, this may more an issue in the dependency library. 

Looks to be addressed here with optional parameters (Not yet live): https://github.com/waylaidwanderer/node-chatgpt-api/pull/308 

> The keepNecessaryMessagesOnly option will help us reduce total memory consumption when using the default in-memory keyv configuration.

**Comment by kuangxiaoye** [comment]
I found a problem. A large number of mongodb writes caused the performance problem this time. I think we can store the conversation content in the browser instead.

Instead of calling savemessage () for every request

reference:https://github.com/mckaywrigley/chatbot-ui

**Comment by danny-avila** [comment]
@kuangxiaoye how much memory are you using? I understand the need for a slim app but i don't think it's unusual for a backend service to handle a large number of writes to mongo. 

I'm not against client side message stores and i may make some optimizations in that direction but abandoning mongo would be a huge refactor.

**Comment by danny-avila** [comment]
> You are right, the memory of my machine has been upgraded from 1.5G to 6G, and sporadic program stops still occur when more than 10 people use it, and there is no error report... I think it may not be a mongo problem, I in debug····

there is a global variable in api\server\routes\ask\askOpenAI.js used to properly abort message streams called `abortControllers`, it will be replaced with redis but you should test if the issue persists by commenting it out.

**Comment by kuangxiaoye** [comment]
ok I'll try.

**Comment by danny-avila** [comment]
@kuangxiaoye For the record, one of the main contributors of this project has their own user system and he does not experience any crashing or memory leaks with 30 simultaneous users.

In my own tests (albeit single user), I could not find any memory leaks.

**Comment by kuangxiaoye** [comment]
> @kuangxiaoye For the record, one of the main contributors of this project has their own user system and he does not experience any crashing or memory leaks with 30 simultaneous users.
> 
> In my own tests (albeit single user), I could not find any memory leaks.

非常感谢你的帮助,我在更换高配服务器之后出现内存泄漏的情况变少了.

**Comment by kuangxiaoye** [comment]
Thank you very much for your help. After I replaced the high-end server, there were fewer memory leaks.

**Comment by kuangxiaoye** [comment]
Thank you very much for your help, I need to troubleshoot my current environmental problems...
