### ISSUE TITLE
Self-Implemented Authentication Support for a Project - Requesting Recognition as Contributor.

### ISSUE THREAD

**Issue by techwithanirudh** [danny-avila/chatgpt-clone#198]
Although authentication support was not included, I took the initiative to implement it myself. It would be wonderful if my contribution could be recognized, perhaps by being added as a contributor or by some other means. You can find the code at https://github.com/techwithanirudh/openai/

**Comment by danny-avila** [comment]
As I mentioned in my PR, Authentication support is already well being worked on. Contributors are only added when they have actually made significant contributions to the project. You should join the discord and see how to contribute to the ongoing effort there https://discord.gg/NGaa9RPCft
