### ISSUE TITLE
chatgpt-clone-api-1 exited with code 1

### ISSUE THREAD

**Issue by mjtechguy** [danny-avila/chatgpt-clone#21]
First off. This is an amazing project. Thanks for putting this together.

I downloaded the latest update (this morning) and I get the following error when deploying with Docker Compose:

```
chatgpt-clone-api-1     | node:events:490
chatgpt-clone-api-1     |       throw er; // Unhandled 'error' event
chatgpt-clone-api-1     |       ^
chatgpt-clone-api-1     | 
chatgpt-clone-api-1     | Error: getaddrinfo EAI_AGAIN "localhost"
chatgpt-clone-api-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
chatgpt-clone-api-1     | Emitted 'error' event on Server instance at:
chatgpt-clone-api-1     |     at GetAddrInfoReqWrap.doListen [as callback] (node:net:1934:12)
chatgpt-clone-api-1     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:17) {
chatgpt-clone-api-1     |   errno: -3001,
chatgpt-clone-api-1     |   code: 'EAI_AGAIN',
chatgpt-clone-api-1     |   syscall: 'getaddrinfo',
chatgpt-clone-api-1     |   hostname: '"localhost"'
chatgpt-clone-api-1     | }
chatgpt-clone-api-1     | 
chatgpt-clone-api-1     | Node.js v19.7.0
```

I have also tried filling in `- HOST=""` in the Docker Compose file with the proper hostname and it is still not working.

Any ideas?

**Comment by mjtechguy** [comment]
I can reach the client UI, and this is the error I see there when it tries to contact the API.

![2023-03-10 10_44_26-Window](https://user-images.githubusercontent.com/29070994/224360192-3bdeb135-4823-47f0-80c1-608b4654f6c2.png)

**Comment by danny-avila** [comment]
I know the issue and working on this!

**Comment by danny-avila** [comment]
I'm glad you've been enjoying this project! I rolled back to latest release since I had trouble debugging how a recent PR affected docker. Will investigate further but for now is confirmed working with docker.
