### ISSUE TITLE
Deprecated Packages in API code

### ISSUE THREAD

**Issue by ocontant** [danny-avila/chatgpt-clone#213]
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
    npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
    npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
    npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.

**Comment by danny-avila** [comment]
> ```
> npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
> npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
> npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
> npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
> ```

I will look into removing the dependencies and maybe even integrating dependabot or something. Will close when this is resolved

**Comment by ocontant** [comment]
dependabot would be a good thing. The errors were the result of the package.json provided in the project and since they had a fixed version it didn't update them. 

Thanks David for the pointer!

**Comment by danny-avila** [comment]
I believe this was Fixed in #244 as I no longer get deprecation warnings for these

**Comment by danny-avila** [comment]
Fully addressed by #319 

Thanks for configuring dependabot @ocontant !
