### ISSUE TITLE
frontend crashed when get code of dotenv

### ISSUE THREAD

**Issue by wtlyu** [danny-avila/chatgpt-clone#22]
![image](https://user-images.githubusercontent.com/8267138/224372136-0cb572c4-e323-4649-b610-5dea07cfc82a.png)

**Comment by danny-avila** [comment]
@wtlyu I had to rollback your recent PR btw. It somehow messed up the docker setup, which I didn't test, and I couldn't figure it out. The goal is to implement what you did, but I'm new to docker and need to test a configuration that works for both local and docker

**Comment by wtlyu** [comment]
> 

i will check tomorrow.

**Comment by wtlyu** [comment]
and what's the problem of docker？ i happen to use it for years.

**Comment by danny-avila** [comment]
it must be the way i have docker setup, I'm new to docker. Whenever you have the time, you could try the same PR again and even reconfig docker if you need to. I thought maybe it was the way I had nginx setup, too, but not sure. I rolled back so I could take more time to investigate without affecting the people using it mainly with docker

**Comment by danny-avila** [comment]
Resolved in PR #32
