### ISSUE TITLE
How do I install via portainer?

### ISSUE THREAD

**Issue by M33ks** [danny-avila/chatgpt-clone#223]
Maybe a dumb question, maybe not even possible, but how would I install this via portainer

**Comment by danny-avila** [comment]
> Worked for me by including the env variables directly in the docker-compose and then adding a stack as normal. Haven't tried it with the latest release.
> 
> version: "3.4" services: api: container_name: chatgpt-clone ports: - 3080:3080 depends_on: - mongodb image: chatgptclone/app:0.3.3 restart: unless-stopped environment: - HOST=0.0.0.0 - PORT=3080 - NODE_ENV=production - MONGO_URI=mongodb://mongodb:27017/chatgpt-clone - OPENAI_KEY=your-api-key - OPENAI_MODELS=gpt-3.5-turbo,gpt-3.5-turbo-0301,text-davinci-003,gpt-4 - SEARCH=TRUE - MEILI_HOST=http://meilisearch:7700 - MEILI_HTTP_ADDR=meilisearch:7700 - MEILI_MASTER_KEY=your-master-key volumes: - /client/node_modules - ./api:/api - /api/node_modules
> 
> mongodb: container_name: chat-mongodb ports: - 27018:27017 image: mongo restart: unless-stopped volumes: - ./data-node:/data/db command: mongod --noauth
> 
> meilisearch: container_name: chat-meilisearch restart: unless-stopped image: getmeili/meilisearch:v1.0 ports: - 7700:7700 environment: - MEILI_HOST=http://meilisearch:7700 - MEILI_HTTP_ADDR=meilisearch:7700 - MEILI_MASTER_KEY=your-master-key volumes: - ./meili_data:/meili_data

Thank you for sharing this, @M33ks i don’t use portainer but I can try for you later. Any success?
