### ISSUE TITLE
How to set the Max token of GPT-4

### ISSUE THREAD

**Issue by fjliss** [danny-avila/chatgpt-clone#229]
I just used GPT-4.0 and prompted the following error, how to solve it?
————
An error occurred. Please try again in a few moments. Error message: Prompt is too long. Max token count is 3071, but prompt is 7752 tokens long.
————
Thank you very much for your help, I am a beginner and would like to be taught by your patience.

**Comment by danny-avila** [comment]
hi @fjliss ! Thanks for trying out the project.

It's not yet supported in the UI but I can walk you through a workaround.

Goto api\app\clients\chatgpt-client.js in your clone of the repo.

edit lines 29 - 35 from this:

```
    modelOptions: {
      model: model,
      temperature,
      top_p,
      presence_penalty,
      frequency_penalty
    },
```

to 
```
    modelOptions: {
      model: model,
      max_tokens: 8000, // or 32k if you have access to that. note this will error for models with lower limits
      temperature,
      top_p,
      presence_penalty,
      frequency_penalty
    },
```
