### ISSUE TITLE
There is no handling of empty data when using getCitations.

### ISSUE THREAD

**Issue by qcgm1978** [danny-avila/chatgpt-clone#231]
I found that sometimes getCitations will report an error, saying `An error occurred. Please try again in a few moments. Error message: Cannot read properties of undefined (reading '0')`. This is because the answer returned by bingAi may not have citation information and requires relevant processing, such as:

```
const getCitations = (res) => {
  const adaptiveCards = res.details.adaptiveCards;
  const textBlocks = adaptiveCards && adaptiveCards[0].body;
  if (!textBlocks) return '';
...
```

**Comment by danny-avila** [comment]
Thansk for this and for checking out the project! I'll make the adjustment when I get the chance. PRs are also welcome!

**Comment by qcgm1978** [comment]
PR has been submitted.
