### ISSUE TITLE
An error occurred. Please try again in a few moments. Error message: Cannot find package 'og-chatgpt-api' imported from /api/app/clients/bingai.js

### ISSUE THREAD

**Issue by tttll1091** [danny-avila/chatgpt-clone#233]
When I ask a question using BingAI, the message in the title is displayed and the process does not work properly

The docker log is below
The text is in Japanese and the token is XXXXXX

chat-clone     | ask log {
chat-clone     |   userMessage: {
chat-clone     |     messageId: '9a695535-b07e-4a17-8c67-0991fd079057',
chat-clone     |     sender: 'User',
chat-clone     |     text: '????????????',
chat-clone     |     parentMessageId: '00000000-0000-0000-0000-000000000000',
chat-clone     |     conversationId: '1a060147-21f0-4c54-9dce-e1918bcb9ea7',
chat-clone     |     isCreatedByUser: true
chat-clone     |   },
chat-clone     |   endpointOption: {
chat-clone     |     jailbreak: false,
chat-clone     |     systemMessage: null,
chat-clone     |     context: null,
chat-clone     |     conversationSignature: null,
chat-clone     |     clientId: null,
chat-clone     |     invocationId: 1,
chat-clone     |     toneStyle: 'fast',
chat-clone     |     token: 'XXXXXX'
chat-clone     |   },
chat-clone     |   conversationId: '1a060147-21f0-4c54-9dce-e1918bcb9ea7'
chat-clone     | }
chat-clone     | Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'og-chatgpt-api' imported from /api/app/clients/bingai.js
chat-clone     |     at new NodeError (node:internal/errors:399:5)
chat-clone     |     at packageResolve (node:internal/modules/esm/resolve:794:9)
chat-clone     |     at moduleResolve (node:internal/modules/esm/resolve:843:20)
chat-clone     |     at ESMLoader.defaultResolve (node:internal/modules/esm/resolve:1058:11)
chat-clone     |     at ESMLoader.resolve (node:internal/modules/esm/loader:323:32)
chat-clone     |     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:172:38)
chat-clone     |     at ESMLoader.import (node:internal/modules/esm/loader:276:22)
chat-clone     |     at importModuleDynamically (node:internal/modules/cjs/loader:1205:37)
chat-clone     |     at importModuleDynamicallyWrapper (node:internal/vm/module:428:21)
chat-clone     |     at importModuleDynamically (node:internal/vm:105:46) {
chat-clone     |   code: 'ERR_MODULE_NOT_FOUND'
chat-clone     | }

**Comment by danny-avila** [comment]
I was able to recreate your issue by simply trying to run docker as normal after an update

I solved it by deleting the chatgpt-clone container, then deleting the node-api image, and running docker-compose up again. This will not delete your data.

This is easy with Docker Desktop but using terminal (make sure you stop the container first):
```
docker stop chatgpt-clone
docker rm chatgpt-clone
```

or
`docker rmi --force node-api`


You can also try from root of your clone, run: 
`docker-compose build` then: `docker-compose up`

**Comment by ssyozi510** [comment]
I did the following but got the same error
---
root@ubuntu:~/chatgpt-clone# docker rmi --force node-api
Untagged: node-api:latest
Deleted: sha256:91042f85a7a77f5a94a440dc313aa71b2d7ace584e29fbd04f373dd88dd9a95c
root@ubuntu:~/chatgpt-clone# docker-compose build
mongodb uses an image, skipping
meilisearch uses an image, skipping
Building api
[+] Building 0.9s (16/16) FINISHED
 => [internal] load .dockerignore                                                                                                 0.0s
 => => transferring context: 64B                                                                                                  0.0s
 => [internal] load build definition from Dockerfile                                                                              0.0s
 => => transferring dockerfile: 1.22kB                                                                                            0.0s
 => [internal] load metadata for docker.io/library/node:19-alpine                                                                 0.8s
 => [internal] load build context                                                                                                 0.0s
 => => transferring context: 14.30kB                                                                                              0.0s
 => [react-client 1/6] FROM docker.io/library/node:19-alpine@sha256:013a0703e961e02b8be69a548f2356ae5b17bc5b8570f1cdd4b97650200b  0.0s
 => CACHED [node-api 2/6] WORKDIR /api                                                                                            0.0s
 => CACHED [node-api 3/6] COPY /api/package*.json /api/                                                                           0.0s
 => CACHED [node-api 4/6] RUN npm ci                                                                                              0.0s
 => CACHED [node-api 5/6] COPY /api/ /api/                                                                                        0.0s
 => CACHED [react-client 2/6] WORKDIR /client                                                                                     0.0s
 => CACHED [react-client 3/6] COPY /client/package*.json /client/                                                                 0.0s
 => CACHED [react-client 4/6] RUN npm ci                                                                                          0.0s
 => CACHED [react-client 5/6] COPY /client/ /client/                                                                              0.0s
 => CACHED [react-client 6/6] RUN npm run build                                                                                   0.0s
 => CACHED [node-api 6/6] COPY --from=react-client /client/dist /client/dist                                                      0.0s
 => exporting to image                                                                                                            0.0s
 => => exporting layers                                                                                                           0.0s
 => => writing image sha256:91042f85a7a77f5a94a440dc313aa71b2d7ace584e29fbd04f373dd88dd9a95c                                      0.0s
 => => naming to docker.io/library/node-api
root@ubuntu:~/chatgpt-clone# docker-compose up
WARNING: Found orphan containers (chatgpt-clone_client_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting chat-meilisearch ... done
Starting chat-mongodb     ... done
Starting chat-clone       ... done
Attaching to chat-meilisearch, chat-mongodb, chat-clone
---
