### ISSUE TITLE
popup window display problem

### ISSUE THREAD

**Issue by wingeva1986** [danny-avila/chatgpt-clone#237]
The popup window of the endpoint will overflow when displayed on a mobile browser, and it cannot be scrolled up or down when overflowing.

![Screenshot_20230511_151009_mark via](https://github.com/danny-avila/chatgpt-clone/assets/35324882/bc30a74f-e556-40e5-936d-4e58207c604b)

![Screenshot_20230511_151026_mark via](https://github.com/danny-avila/chatgpt-clone/assets/35324882/e8e69973-24a6-4e74-9f7b-0c2e4875d265)

**Comment by danny-avila** [comment]
Understood, I have started using it on mobile more with the new update and I see this now too. I will add a scrollbar as a quick fix and look to redesigning it to be more aligned with openai's recent updates
