### ISSUE TITLE
Does this project support chatgpt plus multi tokens?

### ISSUE THREAD

**Issue by Root-FTW** [danny-avila/chatgpt-clone#245]
I have 10 ChatGPT Plus accounts (Don't ask how, but it's thanks to my university).

With this project is it possible to use multiple chatgpt plus tokens?

What I want to achieve is to use the 10 different chatgpt plus tokens that I have and if at some point a token already spent its use of gpt4 automatically use another token.

**Comment by danny-avila** [comment]
Hi, that is a pretty niche case so no, there is no built-in method to rotate tokens for you. However, if you set the following env var in your .env file, you can simply change the token from the UI whenever you wish

```
##########################
# ChatGPT Endpoint: 
##########################

# ChatGPT Browser Client (free but use at your own risk) 
# Access token from https://chat.openai.com/api/auth/session 
# Exposes your access token to `CHATGPT_REVERSE_PROXY`
# Set to "user_provided" to allow the user to provide its token from the UI.
# Leave it blank to disable this endpoint 
CHATGPT_TOKEN="user_provided"
```

![image](https://github.com/danny-avila/chatgpt-clone/assets/110412045/3733e1eb-9a38-4977-a012-23971727ef30)
![image](https://github.com/danny-avila/chatgpt-clone/assets/110412045/392c9aed-def5-490a-9833-1a907a17bc19)

**Comment by danny-avila** [comment]
Awesome! Thanks for trying it out
