### ISSUE TITLE
"Prompt empty or too short" error for cjk languages

### ISSUE THREAD

**Issue by wind2sing** [danny-avila/chatgpt-clone#27]
When I entered "你好" in Chinese, an error message such as "Prompt empty or too short" appeared.
"你好" means hello, and its length is only 2 characters in Chinese.
When we use Chinese input, the length of the phrases we use can be very short, and in these cases, the program may indicate an error.

<img width="525" alt="image" src="https://user-images.githubusercontent.com/66316949/224473880-41dc497b-b4b4-4d16-8b2a-a2ebe1576550.png">

**Comment by wtlyu** [comment]
yep same question here. 
I found that it's the local server reject when question is less than 5 characters. but why?

**Comment by antonme** [comment]
Yeah, that is a problem for non-cjk languages as well
<img width="500" alt="Screenshot 2023-03-11 at 17 31 38" src="https://user-images.githubusercontent.com/1531009/224490385-24169e9a-ddda-4d85-abd7-71f78c2065ab.png">

**Comment by danny-avila** [comment]
This was intentional for testing but it's an easy fix and I can remove it.
