### ISSUE TITLE
 Incorrect styling for customGPT name

### ISSUE THREAD

**Issue by wind2sing** [danny-avila/chatgpt-clone#29]
When using custom name  for a customGPT, the CSS style displayed on the web interface is incorrect.

<img width="689" alt="image" src="https://user-images.githubusercontent.com/66316949/224477902-09452728-dfc0-4409-99c4-14cc2a64f74a.png">

**Comment by danny-avila** [comment]
Can you provide a few examples with your characters so I can test what the expected result should be? In English, the custom name looks fine with `text-align: right;` but I would for sure like to accommodate
