### ISSUE TITLE
An error occurred. Please try again in a few moments. Error message: Google blocked a proper response to your message: {"blocked":true}

### ISSUE THREAD

**Issue by miaoluyao** [danny-avila/chatgpt-clone#290]
An error occurred. Please try again in a few moments. Error message: Google blocked a proper response to your message: {"blocked":true}

**Comment by danny-avila** [comment]
This is not an issue with the repo. It’s triggered by Google’s safety parameters. I’ve error handled this to indicate the blame on Google. It is somewhat strict and gets false positives
