### ISSUE TITLE
The backend program does not provide it. It cannot be linked to the backend

### ISSUE THREAD

**Issue by bukong6** [danny-avila/chatgpt-clone#3]
The backend program does not provide it. It cannot be linked to the backend

**Comment by danny-avila** [comment]
Hi @bukong6, thanks for checking out the project!

You're right, it's not provided. This is still in development/work-in-progress so I haven't made it easily configurable. I will work on easy config/setup instructions next, as well as integrating pocketbase, which is an open source backend in 1 file.

For now, you can either install MongoDB on your host machine or using [Mongo Atlas](https://account.mongodb.com/account/login) which is free. I just tested Atlas and it works great.

In your .env file, set MONGO_URI to your connection string, for example:
`MONGO_URI='mongodb+srv://root.../chatgpt'`

**Comment by danny-avila** [comment]
@bukong6 I'm closing this as I've opted to dockerize the app and provided easy setup instructions with and without docker here: https://github.com/danny-avila/chatgpt-clone#usage

**Comment by bukong6** [comment]
thanks



---Original---
From: "Danny ***@***.***&gt;
Date: Wed, Mar 8, 2023 03:55 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [danny-avila/chatgpt-clone] The backend program does not provideit. It cannot be linked to the backend (Issue #3)




 
@bukong6 I'm closing this as I've opted to dockerize the app and provided easy setup instructions with and without docker here: https://github.com/danny-avila/chatgpt-clone#usage
