### ISSUE TITLE
How can we use the Google Search plugin?

### ISSUE THREAD

**Issue by lsalazarm99** [danny-avila/chatgpt-clone#309]
I followed the steps described [here](https://github.com/danny-avila/chatgpt-clone/blob/main/documents/features/plugins/google_search.md), but I wasn't able to find a way to use the Google Search function. I thought the models would simply use it, but they are still giving wrong information to the classic "who won the last FIFA World Cup" question.

**Comment by danny-avila** [comment]
Plugins are a work in progress, and the feature is not easily configurable in its current state. You would need to git checkout the `langchain` branch and run the project from there, and there is still more configuration.

We are working on making it easily configurable on the frontend, so if there are any authentication methods, as needed with google, it should be straightforward from the app

![image](https://github.com/danny-avila/chatgpt-clone/assets/110412045/43f513f0-e3ec-4e32-8361-aefb53560767)

**Comment by ravi-katiyar** [comment]
Is this completed, can we enable plugins on the frontend ?
