### ISSUE TITLE
client request configuration

### ISSUE THREAD

**Issue by jjdodojohn** [danny-avila/chatgpt-clone#33]
I think it would be better to set the client request url as a settable parameter since we need to replace all "http://localhost:3080" if the client and api are in different machine.

**Comment by DavesDevFails** [comment]
Yeah, probably best to set both SERVER_URL and CLIENT_URL as configurable parameters.

**Comment by wtlyu** [comment]
#26 replace all localhost:3080 request to relative path.
but I agree that SERVER_URL and CLIENT_URL are better design
