### ISSUE TITLE
Fix up the documentation / templates

### ISSUE THREAD

**Issue by ClaraLeigh** [danny-avila/chatgpt-clone#333]
It looks like we need to change the docs structure so that github picks up on the templates.

Here is the pages on it: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

It sounds like we need to either change the folder `/documents` to `/docs` or move templates to `.github`. I think the latter would be better as the foldernames for templates is uppercase which isn't that nice on the eyes.

Doing the latter the tasks would then be:
- [ ] Move the PR template to a folder called `.github/PULL_REQUEST_TEMPLATE`, then we can add more in future
- [ ] Create a directory called `.github/ISSUE_TEMPLATE`
- [ ] Convert the existing issue markdown files to the yaml format github wants (although note I think its in beta and the old one is considered legacy)

**Comment by fuegovic** [comment]
working on it

**Comment by fuegovic** [comment]
PR is submitted

**Comment by ClaraLeigh** [comment]
@fuegovic awesome, I'll take a look. Remember you can always link PRs by putting: #345 somewhere, even in a commit message or description
