### ISSUE TITLE
Opening the conversation menu on mobile is broken

### ISSUE THREAD

**Issue by javon27** [danny-avila/chatgpt-clone#336]
Was testing the app on mobile, and I found that if you try to open the conversation list menu, a grey layer covers the screen and clicking anywhere only dismisses the menu. This means that a user is unable to select specific conversations on any screen smaller than 768px wide (tested with Chrome dev tools). 

It's this element: `<div class="nav-mask active"></div>`. Deleting this element allows you to click the different conversations, but results in errors as the code seems to be expecting this element to exist.

**Comment by javon27** [comment]
I just found the relevant code in mobile.css:

```
@media (max-width: 767px) {
  .nav {
    width: calc(100% - 60px)  ;
    transition: all 0.5s;
  }
  .nav-mask {
    position: fixed;
    z-index: 996;  <------ deleting this seems to fix it, but i'm not sure what the purpose of setting z-index here
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    background-color: rgba(86, 88, 105, 0.75);
    padding-left: 420px;
    padding-top: 12px;
    opacity: 0;
    transition: all 0.5s;
    pointer-events: none;
  }
```

**Comment by danny-avila** [comment]
Sorry this was overlooked on mobile, and thank you for investigating it further! I just pushed #337, can you confirm this is fixed for you?

**Comment by javon27** [comment]
Lol, you beat me to it. I submitted (and closed) a pull request before seeing this. But yeah, z-index 35 should work as well
