### ISSUE TITLE
[Bug]: Bing Returning Error 

### ISSUE THREAD

**Issue by justjoehere** [danny-avila/chatgpt-clone#378]
### Contact Details

joseph.ours@gmail.com

### What happened?

I'm using the docker install of the repo.  I've followed the instructions.  Last week I was up and running with Palm, Bing, and ChatGPT.  This week, Bing isn't working, I'm getting an error 

`"Oops! Something went wrong. Please try again in a few moments. Here's the specific error message we encountered: /turing/conversation/create: failed to parse response body. <!DOCTYPE html><html dir="ltr" lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:Web="http://schemas.live.com/Web/"><script type="text/javascript" nonce="AMxBGPFf1EfH0ZvdcV4llFdZL5vYZR+Mplq6QZUqTWw=" >//<![CDATA[ si_ST=new Date //]]></script><head><!--pc--><title>Bing</title><meta content="text/html; charset=utf-8" http-equiv="content-type" /><meta name="referrer" content="origin-when-cross-origin" /><link href="/sa/simg/favicon-..."`

I've updated my BINGAI_TOKEN thinking maybe it rotated, it did.  , rebuilt the containers.  Still no luck in getting it to work.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant log output

```shell
//<![CDATA[
chat-clone        | (function() { var accLinkParams ={"accLinkRefreshEndPointUrl":"/orgid/acclink/refresh","isAadAuthenticated":false,"refreshAccountLinkInfoTimeInSeconds":3600,"refreshAccountLinkInfoRetryTimeInSeconds":600,"correlationId":"646f8f60a72740cd8f906ec8b614477e","hasActiveLinkedAccount":false}; AccountLink.init(accLinkParams); })();;
chat-clone        | //]]></script><script type="text/rms" nonce="dNGTW/1ARvMV5imrEwyKGdVF/FwGS52T2jSUbyjLlpQ=">//<![CDATA[
chat-clone        | var sj_appHTML=function(n,t){var f,e,o,r,i,s,h;if(t&&n){var c="innerHTML",l="script",a="appendChild",v="length",y="src",p=sj_ce,u=p("div");if(u[c]="<br>"+t,f=u.childNodes,u.removeChild(f[0]),e=u.getElementsByTagName(l),e)for(o=0;o<e[v];o++)r=p(l),i=e[o],i&&(r.type=i.type=="module"||i.type=="importmap"?i.type:"text/javascript",s=i.getAttribute(y),s?(r.setAttribute(y,s),r.setAttribute("crossorigin","anonymous")):(r.text=i[c],r.setAttribute("data-bing-script","1")),i.parentNode.replaceChild(r,i));for(h=_d.createDocumentFragment();f[v];)h[a](f[0]);n[a](h)}};
chat-clone        | //]]></script><script type="text/rms" nonce="dNGTW/1ARvMV5imrEwyKGdVF/FwGS52T2jSUbyjLlpQ=">//<![CDATA[
chat-clone        | setTimeout(RedirectErrorPage.init(), 2);;
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by justjoehere** [comment]
So sorry, I can't seem to edit the labels to only select bug.

**Comment by danny-avila** [comment]
@justjoehere no problem with the labels. I think this is a repeat of https://github.com/danny-avila/chatgpt-clone/issues/370

Can you follow the instructions there and confirm? You will need to update your clone to latest

**Comment by justjoehere** [comment]
That indeed fixed the issue.
