### ISSUE TITLE
[Bug]: docker reported the following error

### ISSUE THREAD

**Issue by UPman24** [danny-avila/chatgpt-clone#390]
### What happened?

> [react-client 3/3] run npm run build:
#0 0.845
#0 0.845 > chat frontend @0.4.6 build
#0 0.845 > vite build
#0 0.845
#0 1.537 vite v4.3.8 build production...
#0 1.572 node:internal/process/commit:289
#0 1.572 triggerUncaughtException(error, true /* fromPromise */);
#0 1.572 ^
#0 1.572
#0 1.572 [Error: EPERM: Operation not permitted, scandir '//proc/1/map_files'] {
#0 1.572 Error number: -1,
#0 1.572 Code: "EPERM",
#0 1.572 syscall: 'scandir',
#0 1.572 Path: '//proc/1/map_files'
#0 1.572 }
#0 1.572
#0 1.572 Node.js v19.9.0
#0 1.584 npm error! Lifecycle script `build` fails with error:
#0 1.584 npm error! error: command failed
#0 1.585 npm error! In the workspace: chat-frontend@0.4.6
#0 1.585 npm error! at location: /client
------
Failed to resolve: Process "/bin/sh -c npm run build" did not complete successfully: exit code: 1

how to solve this problem

### Steps to Reproduce

docker-compose up

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UPman24** [comment]
I run everything fine on m1 Mac, but when I migrated to centos this error occurs, how should I fix it.

**Comment by danny-avila** [comment]
It doesn’t look like you’re running the latest updates on the main branch, but if building is the issue, and it happens only on centos, you can try composing docker from the latest image from dockerhub. Edit this part of your docker-compose file

```
#  image: node-api            # Comment this & uncomment below to build from docker hub image
#    build:
#      context: .
#      target: node-api
   image: chatgptclone/app:latest # Uncomment this & comment above to build from docker hub image
```

**Comment by UPman24** [comment]
> It doesn’t look like you’re running the latest updates on the main branch, but if building is the issue, and it happens only on centos, you can try composing docker from the latest image from dockerhub. Edit this part of your docker-compose file
> 
> ```
> #  image: node-api            # Comment this & uncomment below to build from docker hub image
> #    build:
> #      context: .
> #      target: node-api
>    image: chatgptclone/app:latest # Uncomment this & comment above to build from docker hub image
> ```

I pulled the latest image you just replied to me on centos, and it can run, but the above error will appear when pulling the local project to download and build and run the docker-compose up command, which makes me a little confused

**Comment by danny-avila** [comment]
> > It doesn’t look like you’re running the latest updates on the main branch, but if building is the issue, and it happens only on centos, you can try composing docker from the latest image from dockerhub. Edit this part of your docker-compose file
> > ```
> > #  image: node-api            # Comment this & uncomment below to build from docker hub image
> > #    build:
> > #      context: .
> > #      target: node-api
> >    image: chatgptclone/app:latest # Uncomment this & comment above to build from docker hub image
> > ```
> 
> I pulled the latest image you just replied to me on centos, and it can run, but the above error will appear when pulling the local project to download and build and run the docker-compose up command, which makes me a little confused

Honestly I’m not sure either. I searched your issue and it could be multiple things in your local environment during build time, permissions related or npm related (the files being used by another process)

When you pull from dockerhub, it is running a prebuilt image so it doesn’t run into any of these issues

**Comment by danny-avila** [comment]
It works fine for me when I pull latest and build locally. I always make sure to use `docker-compose build` first and then `docker-compose up` and if that doesn’t work, I delete the container and node-api image and start with up
