### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Carnotaurus454** [danny-avila/chatgpt-clone#395]
### Contact Details

jacksonhelm71@gmail.com

### What happened?

After using the toggle sidebar feature on windows, the side bar boxes become permanently extened. 

### Steps to Reproduce

1. Reload the page.
2. Toggle the sidebar with the button on the top left.

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Hi, can you post a screenshot of what you mean? You can copy paste images on GitHub into the text box

**Comment by danny-avila** [comment]
I tested this on Edge, no issues. After thinking about your comment, do you mean you want the browser to remember the sidebar position?

**Comment by fuegovic** [comment]
@danny-avila I think you're right, I'm pretty sure this is about the fact that the state of the sidebar is not saved in memory
