### ISSUE TITLE
question： dynamic language support

### ISSUE THREAD

**Issue by wtlyu** [danny-avila/chatgpt-clone#40]
i noticed when using official chatgpt, i will get title with the same language.
but in this project, only English title will be generated. even though i talk with chatgpt using Chinese

**Comment by danny-avila** [comment]
Great call. The titling function is basically a standalone call to gpt-turbo as a 'titler', and I can adjust the parameters for titling in the user language.

**Comment by wtlyu** [comment]
No it's not fixed. It failed on my test. mostly is still english.

**Comment by wtlyu** [comment]
Give some example (meaning less):

白菜好吃吗
白菜炒鸡蛋怎么做
如何安装express
Qt这个库怎么样
