### ISSUE TITLE
[Bug]: 0.4.7 - npm run backend - bad auth : authentication failed

### ISSUE THREAD

**Issue by psarno** [danny-avila/chatgpt-clone#407]
### Contact Details

[withheld]

### What happened?

I followed all directions.  I am running `meilisearch.exe` with the proper --master-key.

My .env file has all of the proper security keys:

- MEILI_MASTER_KEY
- BINGAI_TOKEN
- OPENAI_KEY
- MONGO_URI

SEARCH=false

Note for BINGAI_TOKEN I had to copy the cookie setting as directed in alternate instructions.

On `npm run backend` I get:

> chatgpt-clone@0.4.7 backend
> cd api && npm run start

> chat-backend@0.4.7 start
> node server/index.js

> There was an uncaught error: bad auth : authentication failed
> Clearing sync timeouts before exiting...
> npm ERR! Lifecycle script `start` failed with error: 
> npm ERR! Error: command failed
> npm ERR!   in workspace: chat-backend@0.4.7
> npm ERR!   at location: C:\Users\psarn\source\repos\chatgpt-clone\api

![image](https://github.com/danny-avila/chatgpt-clone/assets/18640860/d2cc15ad-c54b-4973-afc6-e9cd42b4f716)

WHAT authentication is failing?   All my keys are there and valid.

### Steps to Reproduce

1. Follow All Instructions
2. Run `npm ci`
3. Run `npm run frontend`
4. Run `npm run backend`

Error.

### Relevant log output

```shell
> chatgpt-clone@0.4.7 backend
> cd api && npm run start

> chat-backend@0.4.7 start
> node server/index.js

> There was an uncaught error: bad auth : authentication failed
> Clearing sync timeouts before exiting...
> npm ERR! Lifecycle script `start` failed with error: 
> npm ERR! Error: command failed
> npm ERR!   in workspace: chat-backend@0.4.7
> npm ERR!   at location: C:\Users\psarn\source\repos\chatgpt-clone\api
```

### Screenshots

![image](https://github.com/danny-avila/chatgpt-clone/assets/18640860/9d58a1ca-91f6-4763-9101-1096f553cb29)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
make sure you formated your mongodb uri properly in the /api/.env file
like this:
`MONGO_URI= mongodb+srv://USERNAME:PASSWORD@chatgpt-clone.maggftx.mongodb.net/?retryWrites=true`

(without < > around the password)

**Comment by psarno** [comment]
This was indeed an issue with the Mongo password formatting.

I wish it indicated with auth was failing, but moving on!  👍
