### ISSUE TITLE
The "ENTER" key does not work as it should

### ISSUE THREAD

**Issue by lucasbr15** [danny-avila/chatgpt-clone#44]
**Describe the bug**
"I'm not sure if it's actually a bug or intentional, but when typing a message and hitting "ENTER" instead of sending the message, it just creates a new line, like when we press (SHIFT+ENTER)."

**Expected behavior**
I hope it works as it should, when typing a message and hitting "ENTER" it should send our request and not break to a new line. It should work like ChatGPT or any other chat bot does

![Screenshot_2](https://user-images.githubusercontent.com/97372669/224516548-81fe6848-86e5-4a8e-9b91-f724b0f26ee5.jpg)

**Comment by lucasbr15** [comment]
I found the cause of the error: the extension "Absolute Enable Right Click & Copy", installed in my Google Chrome, was activated on "localhost" and causing problems. I just disabled it on that domain, and now everything is working normally. Thanks!

**Comment by danny-avila** [comment]
Great, hope you find this project helpful!
