### ISSUE TITLE
Create default conversation before first replay

### ISSUE THREAD

**Issue by wtlyu** [danny-avila/chatgpt-clone#46]
hi @danny-avila , I'm trying to make chatgpt-clone to create a temp conversation named 'New Chat' whenever user ask, especially before the first reply is complete. That is how official chatgpt behave. Do you have any idea on how to do that?

I noticed that in ask.js, the conversation is created based on gptResponse obj, and it require the conversationId.

**Comment by danny-avila** [comment]
You could have the server generate a temp conversationId at the start or before the [progressCallback](https://github.com/danny-avila/chatgpt-clone/blob/master/api/server/routes/ask.js#L67) as that handles the response streaming, the request response is generated [here:](https://github.com/danny-avila/chatgpt-clone/blob/master/api/server/routes/ask.js#L89)


I mean to refactor the progress handling to a separate module that all the files can use, the current design is an artifact from when I was using 2 separate chatgpt client libraries

**Comment by wtlyu** [comment]
It seems that when the first request send, the conversation is created (maybe not in backend, only in frontend, because it seems to have the conversation Id after the first complete reply)

It is useful because we cannot go back the the previous, unfinished conversation before the first replay is finished. The user will lost the conversation unless refresh the website.

How to test:
write a new chat, and switch to another conversation, before the first reply finish.

Another test
write a new chat, and click new chat, before the first reply finish. Then write another new chat. now you will lost the previous one.
