### ISSUE TITLE
Bug of chatgptCustom

### ISSUE THREAD

**Issue by wtlyu** [danny-avila/chatgpt-clone#48]
bug 1:
When save and submit a new chatgptCustom, there is nothing added to the model menu, unless refresh

bug2:
when have multiple chatgptCustom, deleted one of them, it looks like another one is deleted. （but after refresh, everything got correct）

BTW, what's the differencee between save and submit? I got confused.

**Comment by danny-avila** [comment]
Save is to save the model to the menu, submit would selects the customGPT, whether it's saved or not, allowing use for a one-off. I can call it select to make more sense.

Also i'm working on this now. I've got the first issue fixed, but I can't reproduce the 2nd. deleting works as expected for me (maybe the fix i applied to the first fixes both?)

**Comment by wtlyu** [comment]
really? is it designed to have only one customGPT? or it maybe a side effect of bug1

**Comment by danny-avila** [comment]
No I was mistaken, it was a simple oversight with React losing track of the models due to improper keys. They are now tied to their db keys so it shouldn’t happen anymore
