### ISSUE TITLE
Multi-user system

### ISSUE THREAD

**Issue by wtlyu** [danny-avila/chatgpt-clone#49]
Hi @danny-avila , I wanna if you need a PR containing a multi-user system? I have wrote a simple one and it's somehow extendable for future development. 

For now, that's what in my implementation:

1. add a multi-user system, including login, logout and an API `/api/me`
2. UI will display username at the left bottom
3. Conversation will be connected to the username, so they will not see others' conversation.
4. The multi-user system is super simple, it based on session.user, containing {display, username}. the display will be used as display name, and the username will be used as a unique string in database.
5. The login and logout endpoint is not truly implemented, because I use OIDC to connect to my own user center server, so login and logout will redirect to the right place. (but I cannot provide the OIDC part. it's plugin design in order to using any other external auth system, just implement the login and logout, and set the session.user as expected.)

**Comment by danny-avila** [comment]
sure i can take a look. It's not a huge priority right now for me, i'd like to get started on fixing some current issues and search

**Comment by wtlyu** [comment]
#59

**Comment by antonme** [comment]
I support this by a lot. It would be enough for me if authentication is handled by external tools like KeyCloak or Authentik. All ChatGPT-clone needs to do is to save the config and chat history to a different location by getting the username from the headers

**Comment by wtlyu** [comment]
> I support this by a lot. It would be enough for me if authentication is handled by external tools like KeyCloak or Authentik. All ChatGPT-clone needs to do is to save the config and chat history to a different location by getting the username from the headers

yes I'm 90% confident that this PR will match your requirement .

Anther 10% has just been push [49242fe](https://github.com/danny-avila/chatgpt-clone/pull/59/commits/49242febadf9ba5953f5959147afb76072b69136), containing the guide on how to ask gpt to write a proper user system code to connect KeyCloak or Authentik

enjoy

**Comment by wtlyu** [comment]
#59
