### ISSUE TITLE
bug: lost unfinished reply

### ISSUE THREAD

**Issue by wtlyu** [danny-avila/chatgpt-clone#50]
1. ask a question
2. leave the conversation before finished
3. goback the the conversation before finish
4. we will not see the reply, unless refresh.

**Comment by wtlyu** [comment]
Is it possible to fix?

**Comment by danny-avila** [comment]
The unfinished reply can display without refreshing if you click on another conversation after the initial response is done, but I see what you mean about the placeholder

**Comment by wtlyu** [comment]
#55 may fix this

**Comment by danny-avila** [comment]
FYI the unfinished replies don't get lost, they just don't get rendered until conversationId state gets updated

https://user-images.githubusercontent.com/110412045/224862891-3afb6b1c-f1ac-45d0-b486-6da7154a5a07.mp4
