### ISSUE TITLE
Enable default focus on input field in prompt line to improve user experience

### ISSUE THREAD

**Issue by antonme** [danny-avila/chatgpt-clone#58]
Presently, the prompt line does not have automatic focus by default. Consequently, you are required to manually click on the input field before they can begin typing, which leads to slower performance and disallows the use of keyboard-only interactions. 

In contrast, in the original ChatGPT interface, as well as in the default Bing and Poe interfaces, the input field has automatic focus from the outset, allowing for immediate keyboard use without the need for any additional clicks.

**Comment by danny-avila** [comment]
Great point, thank you for bringthis up. Textarea has an autofocus attribute that should do it!

**Comment by wtlyu** [comment]
> Great point, thank you for bringing this up. Textarea has an autofocus attribute that should do it!

🤣🤣🤣🤣 Intersting time point.

It seems I'm the real chatGPT writing code..
