### ISSUE TITLE
Pressing Return with an empty prompt to open assistants (models) menu

### ISSUE THREAD

**Issue by antonme** [danny-avila/chatgpt-clone#61]
Currently, it's not possible to select an assistant using only the keyboard. Instead, you have to click on the assistant icon, which may not be obvious to all users. My proposal is to make the assistant menu appear when the user presses the "return" key without typing anything in the input field. This would make it easier to choose an assistant without needing to use the mouse, and it may also be more discoverable than having to click on the assistant icon manually

**Comment by wtlyu** [comment]
Excuse my english level, what is the assistant? (just curious

**Comment by danny-avila** [comment]
I think this is a great idea, I will move it to the discussion point you made already.

**Comment by wtlyu** [comment]
Why not try Shift + Tab, then press Enter. It's already functional
