### ISSUE TITLE
code view seems to be buggy

### ISSUE THREAD

**Issue by wtlyu** [danny-avila/chatgpt-clone#69]
I found that the code view is somehow not stable enough,

1. if the response is writing like 
```
```some code here... still writing
```

then the code view disappear , until the end three dots comes.

2. It cannot guess the language, but the official chatgpt can. ( I have checked )
3. It cause a safety issue that the html code will be rendered directly , for example

```
    ```html\n' +
    <div class="container">\n' +
      <h1>Welcome to my website!</h1>\n' +
    </div>\n' +
    ```',
```

<img width="589" alt="image" src="https://user-images.githubusercontent.com/8267138/225108399-b0d3f77b-1164-4fd2-bb6d-4446be6d72bd.png">

**Comment by danny-avila** [comment]
1. This is already on my radar but we can leave this open to address later. The solution would be server-side in the progress callback, which im currently refactoring in your branch.
2. the language detection uses a free library. We can use chatgpt but it will cost tokens (and possibly longer response time). ChatGPT is fickle as to when it appends the language to the triple-backticks. Note: highlight.js also does a better job detecting but it causes too much of a slowdown on the client side. maybe there's a way to use h.js on the server instead.
3. this is an easy fix and I'm waiting on merging your PR bug-free before getting to this

**Comment by wtlyu** [comment]
sure. I noticed when asking some html and css question ,the frontend is always crashing. Escape the response code is dangerous which shouldn't be used.

**Comment by danny-avila** [comment]
somewhat related to #67 I'm weighing different options for a complete rewrite of markdown/code handling, should help with this issue too.

**Comment by danny-avila** [comment]
this shouldnt happen anymore, html should be disabled inside of code blocks too
