### ISSUE TITLE
Error message: citationRegex is not defined

### ISSUE THREAD

**Issue by wind2sing** [danny-avila/chatgpt-clone#73]
When I ask a question using Bing, I find the following error:
![image](https://user-images.githubusercontent.com/66316949/225494071-a120ea5f-7a10-4c3a-9ba0-14a04fb4c7aa.png)

```
ReferenceError: citationRegex is not defined
    at ask (/home/runner/chatGPT/chatgpt-clone/api/server/routes/askBing.js:99:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/runner/chatGPT/chatgpt-clone/api/server/routes/askBing.js:43:10

```
And there are no issues when I ask a question using Sydney.

![image](https://user-images.githubusercontent.com/66316949/225494727-d82471ce-6e24-4d33-b5ef-5eb8aea740da.png)

**Comment by danny-avila** [comment]
Thanks, this was just an oversight on my part. I'll fix this now and commit

**Comment by danny-avila** [comment]
Fixed on master branch!
