### ISSUE TITLE
refactor to support regenerate and stop generating.

### ISSUE THREAD

**Issue by wtlyu** [danny-avila/chatgpt-clone#78]
FYI, I'm working on this, and will send a PR soon @danny-avila

**Comment by wtlyu** [comment]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/8267138/225709844-ffdb75c4-ec30-49ef-8ef1-a47ab3055ab5.png">

**Comment by danny-avila** [comment]
nice, I merged your last PR with styling changes to the icons and textarea btw

**Comment by wtlyu** [comment]
#80
