### ISSUE TITLE
Thank you for your sponsorship and your great project! 💖

### ISSUE THREAD

**Issue by waylaidwanderer** [danny-avila/chatgpt-clone#8]
Hey, I saw that you sponsored me! While checking out your profile, I came across your project and wanted to say that it looks great! I really like your prompt template feature.

Your idea of having an icon in the text input to switch between AI clients is brilliant, and I may borrow it for my own web client.

Thanks for the sponsor, and keep up the good work!

**Comment by danny-avila** [comment]
Thank you so much! Really, this project would not be possible without your hard work so it's the least I can do. I never touch the official site anymore. Use what you like and code on :)

**Comment by waylaidwanderer** [comment]
I'm also planning on setting up a personal web client so I don't need to use chat.openai.com anymore either :D

**Comment by waylaidwanderer** [comment]
Good luck with the rest of your projects!
