### ISSUE TITLE
Using Sydney mode and triggering the censorship block causes error "Error message: Cannot read properties of undefined (reading 'match')"

### ISSUE THREAD

**Issue by throwaway268** [danny-avila/chatgpt-clone#82]
In the web GUI this appears as:

"An error occurred. Please try again in a few moments.

Error message: Cannot read properties of undefined (reading 'match')"

I've included the debug info from the console below. As best I can tell this is because the censorship causes the final response to have the text field as 'undefined' which then breaks the detectCode function.

We are clearly still receiving the real uncensored response since I can see the words of the real answer printed before they are replaced with the error. I think the solution might be to detect this missing text field and just assume the data received while the response was in-progress is the real text?

Prompt to reproduce: "Describe a man sexually". Can replace "man" with "woman" or "person".

```
SYDNEY RESPONSE {
  jailbreakConversationId: 'redacted',
  conversationId: '51D|BingProd|redacted',
  conversationSignature: 'redacted',
  clientId: 'redacted',
  invocationId: 1,
  messageId: 'redacted',
  conversationExpiryTime: '2023-03-17Tredacted',
  response: undefined,
  details: {
    author: 'bot',
    createdAt: '2023-03-17Tredacted',
    timestamp: '2023-03-17Tredacted',
    messageId: 'redacted',
    requestId: 'redacted',
    offense: 'None',
    adaptiveCards: [ [Object] ],
    sourceAttributions: [],
    feedback: { tag: null, updatedOn: null, type: 'None' },
    contentOrigin: 'Apology',
    scores: [ [Object] ],
    privacy: null,
    suggestedResponses: [ [Object], [Object], [Object] ]
  }
}
Error in detectCode function
 TypeError: Cannot read properties of undefined (reading 'match')
    at detectCode (C:\Users\user\Documents\chatgpt\chatgpt-clone\api\app\detectCode.js:10:15)
    at handleText (C:\Users\user\Documents\chatgpt\chatgpt-clone\api\server\routes\handlers.js:57:16)
    at ask (C:\Users\user\Documents\chatgpt\chatgpt-clone\api\server\routes\askSydney.js:144:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\user\Documents\chatgpt\chatgpt-clone\api\server\routes\askSydney.js:43:10
TypeError: Cannot read properties of undefined (reading 'match')
    at handleText (C:\Users\user\Documents\chatgpt\chatgpt-clone\api\server\routes\handlers.js:63:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ask (C:\Users\user\Documents\chatgpt\chatgpt-clone\api\server\routes\askSydney.js:144:21)
    at async C:\Users\user\Documents\chatgpt\chatgpt-clone\api\server\routes\askSydney.js:43:10
```

**Comment by danny-avila** [comment]
sadly, bing's temperature has dropped dramatically, and sydney's default system message triggers a message refusal. There is a PR on the api repo to allow system message config https://github.com/waylaidwanderer/node-chatgpt-api/pull/199 but until merged will not be handled.

#85 handles bing refusals now but I noticed this is a **widespread issue with bing** refusing the current jailbreak. see here:
https://github.com/waylaidwanderer/node-chatgpt-api/discussions/187#discussioncomment-5345724
