### ISSUE TITLE
scroll to bottom, looks to be hesitantly

### ISSUE THREAD

**Issue by wtlyu** [danny-avila/chatgpt-clone#91]
when new message is receiving, especially add new lines too quick, the auto scroll to end behaves to be hesitantly, and cannot scroll fast enough to the end. 

this is mostly happened in mobile version. you can try write me a poem

here is a video. you can see the scroll cannot match the end starting from the second response, while responding.

I think it's because we call scrolltoend too much. 
maybe we can detect scrolltop of the end element and skip some scrolltoend call if not changed. (might not fix completely)

**Comment by wtlyu** [comment]
https://user-images.githubusercontent.com/8267138/226084336-0ec9718e-b9e2-4ac7-b30e-af9c749b05d0.mp4

**Comment by wtlyu** [comment]
another solution maybe set the scrollTop by hand, and set scrollTop target when responding

**Comment by danny-avila** [comment]
> 

sadly I can't see the video. try uploading on discord. could also throttle the scrolltobottom function

**Comment by Samit-prsl** [comment]
hey can i work on this?

**Comment by danny-avila** [comment]
> hey can i work on this?

I throttled the function in my latest branch to fire every 750ms. It looks smother on my end but I can’t reproduce the exact visual bug so if you can go for it!

**Comment by danny-avila** [comment]
@wtlyu how does this look on main now?
