### ISSUE TITLE
Error in GptBrowser model after upgrade

### ISSUE THREAD

**Issue by darrellfonge** [danny-avila/chatgpt-clone#96]
After i upgrade client and api code appear an Error in GptBrowser model
before upgrade code this was work perfectly

![error](https://user-images.githubusercontent.com/127983084/226176323-115c4659-d5a1-4c90-9ff2-1c332f9981a0.jpg)

**Comment by wtlyu** [comment]
may related to my modification. I will try to fix it but need days.

**Comment by danny-avila** [comment]
this was an easy fix. I will push to master when the rest of my debugging for the night is done. if you want a head start, you can try using the branch im working on but im actively making changes there

https://github.com/danny-avila/chatgpt-clone/tree/moon-walk

**Comment by danny-avila** [comment]
Merging fix to master in #99 , confirmed working
