### ISSUE TITLE
forwarding to /auth/login/ although user system environment variable not activated

### ISSUE THREAD

**Issue by 0evers** [danny-avila/chatgpt-clone#97]
I installed the latest version (0.0.5) in Docker and left the environment variable empty. For half a second the main page is visible as an anonymous user before I am redirected to the login.

**Comment by danny-avila** [comment]
Are you still able to navigate/use the app as expected?

**Comment by 0evers** [comment]
> Are you still able to navigate/use the app as expected?

No, it always tries to redirect to the login page.

**Comment by danny-avila** [comment]
no issue here on master branch with a clean compose and docker. make sure you have your .env file in the api dir.
These are the variables i have set. anything else is omitted from the file

PORT=3080
OPENAI_KEY=
MONGO_URI='mongodb://127.0.0.1:27017/chatgpt-test'
NODE_ENV=development
BING_TOKEN=
CHATGPT_TOKEN=

**Comment by 0evers** [comment]
> no issue here on master branch with a clean compose and docker. make sure you have your .env file in the api dir.
> 
> These are the variables i have set. anything else is omitted from the file
> 
> 
> 
> PORT=3080
> 
> OPENAI_KEY=
> 
> MONGO_URI='mongodb://127.0.0.1:27017/chatgpt-test'
> 
> NODE_ENV=development
> 
> BING_TOKEN=
> 
> CHATGPT_TOKEN=

Thank you, but I specified exactly the same environment variables with the keys (I have also just checked these again). If I prohibit redirecting in my browser it works. But every other visitor is immediately redirected.

**Comment by danny-avila** [comment]
Weird. So sorry about that. I’ll try and reproduce the issue. I would also clear storage and browser data just in case. Explicitly setting the ENABLEUSER variable to false may help too. I’ll put it on @wtlyu ‘s radar since he implemented this piece

**Comment by darrellfonge** [comment]
i have same problem too

**Comment by danny-avila** [comment]
@darrellfonge @0evers i commented out code that might trip you up. i reproduced the error but need to know if its all good on your end.

**Comment by darrellfonge** [comment]
you should increase timeout for API call in axios

**Comment by 0evers** [comment]
> Weird. So sorry about that. I’ll try and reproduce the issue. I would also clear storage and browser data just in case. Explicitly setting the ENABLEUSER variable to false may help too. I’ll put it on @wtlyu ‘s radar since he implemented this piece

Sorry, I have not been able to test it as my cpu does not support avx and mongodb has required this for some time so even if it would work, I would have problems. Intel was still releasing cpus that did not support this 4 years ago and mine is unfortunately one of those.

**Comment by danny-avila** [comment]
> Sorry, I have not been able to test it as my cpu does not support avx and mongodb has required this for some time (so even if it would work, I would have problems). Intel was still releasing cpus that did not support this 4 years ago and mine is unfortunately one of those.

are you using docker? a user reported the same issue and said, "you can make it work by setting MongoDB's version to mongo:4.4.18 in docker-compose.yml, the most recent version compatible with"

**Comment by 0evers** [comment]
> > Sorry, I have not been able to test it as my cpu does not support avx and mongodb has required this for some time (so even if it would work, I would have problems). Intel was still releasing cpus that did not support this 4 years ago and mine is unfortunately one of those 
> 
> 
> 
> are you using docker? a user reported the same issue and said, "you can make it work by setting MongoDB's version to mongo:4.4.18 in docker-compose.yml, the most recent version compatible with since MongoDB does not support older ARM CPUs like those found in Raspberry Pis. "

Thanks a lot, it works. But only Bing, not ChatGPT with my Plus subscription and the access token.

```

08:40:35
Error: Failed to send message. HTTP 404 - {"detail":"Conversation not found"}
stdout
08:40:36
    at onopen (file:///api/node_modules/@waylaidwanderer/chatgpt-api/src/ChatGPTBrowserClient.js:102:37)
stdout
08:40:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
stdout
08:40:36
    at async create (file:///api/node_modules/@waylaidwanderer/fetch-event-source/lib/esm/fetch.js:53:17) {
stdout
08:40:36
  status: 404,
stdout
08:40:36
  json: { detail: 'Conversation not found' }
stdout
08:40:36
}
stdout
08:40:36
The client has disconnected.

```

**Comment by danny-avila** [comment]
This is a master branch bug. Are you on main branch?
