### ISSUE TITLE
Support custom Bing AI

### ISSUE THREAD

**Issue by HyunggyuJang** [danny-avila/chatgpt-clone#98]
With https://github.com/waylaidwanderer/node-chatgpt-api/pull/199, the customized system message is back; like custom GPT, we should support custom bing AI.

**Comment by danny-avila** [comment]
Will be part of using the latest node-chatgpt-api and the features i will bring to custom params. I think we can accelerate use of sydney if we get the library working for bing/sydney first through the alias

**Comment by danny-avila** [comment]
sydney/bing is working thanks to you, I will get on this with my update immediately following the search update

**Comment by HyunggyuJang** [comment]
> sydney/bing is working thanks to you, I will get on this with my update immediately following the search update

Looking forward to! I myself also will look into it on my free time! If you are working on a public branch for this feature, might be able contribute.

**Comment by danny-avila** [comment]
Not yet started as I’m finalizing searching messages, which will be a big update. It would be really helpful to have bing/Sydney “ask” routes consolidated and cleaned up and that can be right off main. There’s a good amount of code they share but any divergence could be delegated to imported functions

**Comment by HyunggyuJang** [comment]
> Not yet started as I’m finalizing searching messages, which will be a big update. It would be really helpful to have bing/Sydney “ask” routes consolidated and cleaned up and that can be right off main. There’s a good amount of code they share but any divergence could be delegated to imported functions

So, you mean we can work on the bing/Sydney routes decomposition from the other open AI engines (as those are inherently having different way to interact), right? Okay, while you are working on the search feature (very sweet!), I'll try to understand and how we design it.

**Comment by danny-avila** [comment]
> So, you mean we can work on the bing/Sydney routes decomposition from the other open AI engines (as those are inherently having different way to interact), right? Okay, while you are working on the search feature (very sweet feature!), I'll try to understand and how we design it.

On the backend specifically, they are split into two different endpoints. This was mainly done for convenience as I figured out how the jailbreak work. I think the two are similar enough to consolidate into one endpoint, where they would share most of the same logic, and where it differs can go into separate handler functions in the same directory. 

Having this cleaned up would make it easier to apply custom settings for bing as it can also be in the same endpoint. I plan to use similar language/logic on the front end as with the current customgpt system

**Comment by HyunggyuJang** [comment]
> > So, you mean we can work on the bing/Sydney routes decomposition from the other open AI engines (as those are inherently having different way to interact), right? Okay, while you are working on the search feature (very sweet feature!), I'll try to understand and how we design it.
> 
> On the backend specifically, they are split into two different endpoints. This was mainly done for convenience as I figured out how the jailbreak work. I think the two are similar enough to consolidate into one endpoint, where they would share most of the same logic, and where it differs can go into separate handler functions in the same directory.
> 
> Having this cleaned up would make it easier to apply custom settings for bing as it can also be in the same endpoint. I plan to use similar language/logic on the front end as with the current customgpt system but we can focus on backend to start,
> 
> edit: and by custom bing I mean Sydney’s system message i guess. If you think they should be separate and all custom logic goes to Sydney, I’m fine with that too

Got it! Thanks for your clarification! Now I get the picture. So rather than decomposing, but make use of existing logic if possible. Okay, I’ll try to look into it.

**Comment by Erisfiregamer1** [comment]
You're welcome, by the way.

**Comment by danny-avila** [comment]
> You're welcome, by the way.

Yes, thank you for implementing this in the node library and for finding your way here! I’m working on this now

**Comment by danny-avila** [comment]
Finished in #142

**Comment by HyunggyuJang** [comment]
This is epic! Thanks a lot.
